# Generated by Django 3.0.1 on 2020-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(default='', max_length=70)),
                ('title', models.CharField(default='', max_length=70)),
                ('head0', models.CharField(default='', max_length=70)),
                ('chead0', models.CharField(default='', max_length=7000)),
                ('head1', models.CharField(default='', max_length=70)),
                ('chead1', models.CharField(default='', max_length=7000)),
                ('head2', models.CharField(default='', max_length=70)),
                ('chead2', models.CharField(default='', max_length=7000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='bloggerapp/images')),
            ],
        ),
    ]
